//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthERP.OnlineOrderManagement {
    
    
    public partial class CustomerMFUnitHoldingList {
        
        /// <summary>
        /// scriptmanager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager scriptmanager;
        
        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btnExport;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolio;
        protected global::System.Web.UI.WebControls.Button btnUnitHolding;
        protected global::Telerik.Web.UI.RadGrid rgUnitHolding;
        protected global::System.Web.UI.WebControls.Panel pnlMFUnitHolding;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trNoRecords;
    }
}
