//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthERP.OnlineOrderBackOffice {
    
    
    public partial class OnlineNCDOrderMatchExceptionHandling {
        
        /// <summary>
        /// scrptMgr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager scrptMgr;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.TextBox txtTo;


        protected global::Telerik.Web.UI.RadGrid gvOrders;
        protected global::System.Web.UI.WebControls.Panel pnlGrid;
        protected global::System.Web.UI.WebControls.Panel pnlBtns;


        
        /// <summary>
        /// ddlProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlProduct;

        protected global::System.Web.UI.WebControls.DropDownList ddlOrderStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlIssue;

        
        /// <summary>
        /// RequiredFieldValidator3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    }
}
